server:
  port: 11011

master:
  ip: 127.0.0.1

spring:
  application:
    name: springcloud-business
  datasource:
    source1:
      driverClass: com.mysql.jdbc.Driver
      url: jdbc:mysql://${master.ip}:3306/db1?&useSSL=false&characterEncoding=utf8
      username: root
      password: 123
    source2:
      driverClass: com.mysql.jdbc.Driver
      url: jdbc:mysql://${master.ip}:3306/db2?&useSSL=false&characterEncoding=utf8
      username: root
      password: 123


eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
