server:
  port: 11011

spring:
  application:
    name: springcloud-business

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/