server:
  port: 11011

spring:
  application:
    name: springcloud-business

eureka:
  instance:
    hostname: 192.168.9.27
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${custom.localIp}:8761/eureka/

custom:
  localIp: 192.168.9.27