server:
  port: 11011

spring:
  application:
    name: springcloud-business

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.9.27:8761/eureka/