server:
  port: 8761

spring:
  application:
    name: springcloud-eureka

eureka:
  instance:
    hostname: 192.168.9.27
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${custom.localIp}:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    # 关闭自我保护机制
    enable-self-preservation: false

custom:
  localIp: 192.168.9.27